# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us 983708408@qq.com
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(Test) configuration. ####
#
spring:
  web.cors:
    enabled: true # Defualt: true
    rules:
      - path: /**
        allowCredentials: true
        allowsOrigins:
           - https://*.${DEVOPS_DOMAIN_TOP:wl4g.test}
           - http://*.${DEVOPS_DOMAIN_TOP:wl4g.test}
           - http://10.0.0.160:38099
        allowsHeaders: '*'
        allowsMethods: GET,POST,OPTION
  cloud:
    devops:
      iam: # IAM configuration.
        #login-uri: /view/login.html
        login-uri: http://devops.${DEVOPS_DOMAIN_TOP:wl4g.test}/#/login
        unauthorized-uri: /view/403.html
        success-endpoint: umc-manager@http://umc.${DEVOPS_DOMAIN_TOP:wl4g.test}/umc-manager
        authc-internal-access:
          secure: false # Turn off protection will trust any same intranet IP.
          allowIp: 127.0.0.1
          denyIp:
        captcha:
          #jigsaw:
            #source-dir: ${server.tomcat.basedir}/data/jigsaw-maternal
        sns: # SNS configuration.
          oauth2-connect-expire-ms: 60_000 # oauth2 connect processing expire time
          wechat-mp:
            app-id: wxec3f74a4062d650f
            app-secret: 705595b5807d69e643d6e15fd7350499
            redirect-url: http://passport.wl4g.com${server.contextPath}/sns/wechatmp/callback
          wechat:
            app-id: wx162814f9191f9d9b
            app-secret: 9f1d914629bd9820351fb73f51e70495
            redirect-url: http://passport.wl4g.com${server.contextPath}/sns/wechat/callback
            href: https://static.wl4g.com:2443/iam/static/wx.css
          qq:
            app-id: 101542056
            app-secret: 46b2ba9fa24c2b973abc64ec898db3b4
            redirect-url: http://passport.wl4g.com${server.contextPath}/sns/qq/callback
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://safecloud-test:30601/devops?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
      username: gzsm
      password: gzsm@%#jh?
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      log-slow-sql: true

# Spring-security config.
security.user:
  name: sba_user
  password: 123456

# Redis configuration.
redis:
  passwd: ${REDIS_PASSWD:zzx!@#$%}
  connect-timeout: 10000
  max-attempts: 10
  # Redis's cluster nodes.
  nodes: ${REDIS_NODES:safecloud-test:6379,safecloud-test:6380,safecloud-test:6381,safecloud-test:7380,safecloud-test:7380,safecloud-test:7381}
